# Generated by Django 4.0.3 on 2022-03-31 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casaslist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_id', to='casaslist_app.empresa'),
        ),
    ]
