# Generated by Django 4.0.3 on 2022-03-31 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casaslist_app', '0002_casa_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='sitioWeb',
            new_name='website',
        ),
        migrations.AlterField(
            model_name='casa',
            name='empresa',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='empresas_list', to='casaslist_app.empresa'),
        ),
    ]
