# Generated by Django 4.0.3 on 2022-04-10 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('casaslist_app', '0004_alter_casa_empresa_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comentario_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
