# Generated by Django 4.0.3 on 2022-04-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casaslist_app', '0005_comentario_comentario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='avg_calificacion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='casa',
            name='cantidad_calificaciones',
            field=models.IntegerField(default=0),
        ),
    ]
